services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis
    volumes:
      - ./data/cache:/data
  
  web:
    build: .
    command: ['./wait-for-it.sh', 'db:5432', '--', 'uwsgi', '--ini', '/code/config/uwsgi/uwsgi.ini']
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - SECRET_KEY='andrew_krutsch--1q!qa9rgg16j74__qxp5aw(q1*7sz@ow5)!6nt5!cb9gm7yb!'
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DEFAULT_FROM_EMAIL=andr.krutsch@gmail.com
    depends_on:
      - db
      - cache

  nginx:
    image: nginx
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - '80:80'
      - '443:443'

  daphne:
    build: .
    working_dir: /code/educa/
    command: ['../wait-for-it.sh', 'db:5432', '--', 'daphne', '-b', '0.0.0.0', '-p', '9001', 'educa.asgi:application']
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - SECRET_KEY='andrew_krutsch--1q!qa9rgg16j74__qxp5aw(q1*7sz@ow5)!6nt5!cb9gm7yb!'
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DEFAULT_FROM_EMAIL=andr.krutsch@gmail.com
    depends_on:
      - db
      - cache