# Generated by Django 5.0.7 on 2024-07-31 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('temp',)},
        ),
        migrations.RenameField(
            model_name='module',
            old_name='order',
            new_name='temp',
        ),
    ]
