# Generated by Django 5.0.7 on 2024-07-31 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_module_options_rename_order_module_temp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('order',)},
        ),
        migrations.RenameField(
            model_name='module',
            old_name='temp',
            new_name='order',
        ),
    ]
